[versions]
kotlin = "2.3.0"
kotlinx-serialization = "1.9.0"
ktor = "3.3.2"
logback = "1.4.14"
kvision = "9.3.0"
gw2api = "0.10.0"
flexmark = "0.64.8"
napier = "2.7.1"
juul-indexeddb= "0.11.0"
kottage = "1.10.0"

[libraries]
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
gw2api = { module = "com.gw2tb.gw2api:api-client", version.ref = "gw2api" }
gw2api-ktor = { module = "com.gw2tb.gw2api:api-client-ktor", version.ref = "gw2api" }

kvision = { module = "io.kvision:kvision", version.ref = "kvision" }
kvision-bootstrap = { module = "io.kvision:kvision-bootstrap", version.ref = "kvision" }
kvision-i18n = { module = "io.kvision:kvision-i18n", version.ref = "kvision" }
kvision-testutils = { module = "io.kvision:kvision-testutils", version.ref = "kvision" }

flexmark-java = { module = "com.vladsch.flexmark:flexmark-java", version.ref = "flexmark" }

napier = { module = "io.github.aakira:napier", version.ref = "napier" }

juul-indexeddb = {module="com.juul.indexeddb:core", version.ref="juul-indexeddb"}
kottage = { module="io.github.irgaly.kottage:kottage", version.ref="kottage"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kvision = { id = "io.kvision", version.ref = "kvision" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }

